### ISSUE TITLE
Feature request : Magnetic declination effect

### ISSUE THREAD

**Issue by nawre** [ls4096/libproteus#1]
One could add magnetic declination to the compass reading depending on the location.

https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#declination
https://www.ngdc.noaa.gov/geomag/geomag.shtml

When the user is setting a new course, it should be relative to magnetic north (the direction the north end of a magnetized compass needle points, corresponding to the direction of the Earth's magnetic field lines) and not true north (the direction along a meridian towards the geographic North Pole). The magnetic declination varies depending on position on the Earth's surface and changes over time.

**Comment by ls4096** [comment]
Thank you for the suggestion! This is a great idea, and I think it fits within the scope of what this library is about. It would also be interesting to have such a feature in SailNavSim, and for it to be available to any other potential users of the library as well.

**Comment by ls4096** [comment]
@nawre: Thanks again for the suggestion here. Calculations for estimated magnetic declination for any geographic position and for any time between the years 2020.0 and 2025.0 (for now) have been added in libProteus version 0.6.0.

Note that this feature (along with the celestial navigation calculations recently also added to libProteus) will be used by some upcoming changes to sailnavsim-core as well.
