### ISSUE TITLE
Feature request : Celestial navigation tool

### ISSUE THREAD

**Issue by nawre** [ls4096/libproteus#2]
Let the user the optional possibility to use a celestial navigation tool instead of giving him directly a LAT/LON location and let him report the location manually on a map. One could give the user (when the cloud cover is OK) the altitude/azimuth of 3 stars + moon (at night), the altitude/azimuth of the sun on daylight.

**Comment by ls4096** [comment]
I like this idea, but I think I would prioritise it below the feature request in #1 for now. The main reason being that I imagine this would be considerable effort to implement accurately, and I'm not convinced of its immediate applicability to the major user of this library (SailNavSim) given the astronomical changes that would be required there to support it.

However, relying on celestial navigation in any global navigation simulator would be a fascinating experience, so I will leave this request open for now with the hope that this might be implemented in the future.

**Comment by ls4096** [comment]
@nawre: Thanks again for this suggestion. Some celestial calculations can now be performed in libProteus v0.5.0. This version adds support for the following:

1. Calculation of equatorial coordinates for the Sun and the 20 brightest navigational stars plus Polaris, for a given time instant.
2. Calculation of horizontal coordinates, for given equatorial coordinates, geographic position, time instant, and with an optional atmospheric refraction modification.
